title: Open Design Kit
exclude: [README.md, Gemfile, Gemfile.lock, CNAME, params.json]
collections:
    methods:
        output: true
        permalink: /methods/:path/
    i18n:
        output: false
permalink: title
